<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TierRepository extends EntityRepository
{

  public function findTiersOrderedByMinRange()
  {
	return $this->getEntityManager()
	  ->createQuery(
		'SELECT t FROM AppBundle:Tier t ORDER BY t.minRange ASC'
	  )
	  ->getResult();
  }
}
