<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TierRepository extends EntityRepository
{
}
